// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOY0guC9UYj4bvI1iwWlgInRSYbJnfwfE',
    appId: '1:969312745798:web:47c84f439d91c47bc98d47',
    messagingSenderId: '969312745798',
    projectId: 'trident-98a49',
    authDomain: 'trident-98a49.firebaseapp.com',
    storageBucket: 'trident-98a49.firebasestorage.app',
    measurementId: 'G-PBLB6EGQFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASgKAFt9jjB30OPHpqmslOCpPhAawRefU',
    appId: '1:969312745798:android:4a2fdebf1d215a85c98d47',
    messagingSenderId: '969312745798',
    projectId: 'trident-98a49',
    storageBucket: 'trident-98a49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGQ5isGSIxM35LIPdQSbZdr0o8Dsk-QKw',
    appId: '1:969312745798:ios:a8f3a1171719b357c98d47',
    messagingSenderId: '969312745798',
    projectId: 'trident-98a49',
    storageBucket: 'trident-98a49.firebasestorage.app',
    iosBundleId: 'com.example.trident',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGQ5isGSIxM35LIPdQSbZdr0o8Dsk-QKw',
    appId: '1:969312745798:ios:a8f3a1171719b357c98d47',
    messagingSenderId: '969312745798',
    projectId: 'trident-98a49',
    storageBucket: 'trident-98a49.firebasestorage.app',
    iosBundleId: 'com.example.trident',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOY0guC9UYj4bvI1iwWlgInRSYbJnfwfE',
    appId: '1:969312745798:web:528a9ca01d074071c98d47',
    messagingSenderId: '969312745798',
    projectId: 'trident-98a49',
    authDomain: 'trident-98a49.firebaseapp.com',
    storageBucket: 'trident-98a49.firebasestorage.app',
    measurementId: 'G-D1VG9N9G82',
  );
}
